import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import ThemeProvider from "../providers/theme-provider";
import '@ant-design/v5-patch-for-react-19'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Layout } from "antd";
import LayoutProvider from "@/providers/layout-provider";
import { ConfigProvider } from "antd";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Donations app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider>
            <ConfigProvider>
              <LayoutProvider>{children}</LayoutProvider>
            </ConfigProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
